// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-oasis/HeroBold.tsx": () => import("../components/mockups/hero-oasis/HeroBold.tsx"),
  "./components/mockups/hero-oasis/HeroClean.tsx": () => import("../components/mockups/hero-oasis/HeroClean.tsx")
};
